# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/testdriven-app
    steps:
      - checkout
      - run:
          name: Build User Container
          command: docker-compose up -d --build
      - run:
          name: Run Unit Tests with Coverage inside User Container
          command: |
            mkdir -p /tmp/test-reports
            docker-compose exec users python manage.py cov > /tmp/test-reports/test-reports.log
      - run:
          name: Run QA Tests -- Linting
          command: |
            docker-compose exec users flake8 project >> /tmp/test-reports/test-reports.log
      - store_artifacts:
          path: /tmp/test-reports