# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/python:3.7.4
    working_directory: '~/testdriven-app'

jobs:
    build:
        executor: my-executor
        steps:
            - checkout
            - setup_remote_docker:
            - run:
                name: Build Containers
                command: docker-compose up -d --build
            - run:
                name: Run Unit Tests inside Container
                command: docker-compose exec users python manage.py test
            - run:
                name: Code Quality -- Linting and Coverage
                command: docker-compose exec users flake8 project